name: The Key
favicon: null
layout_spectrum: 0.275273225735873
typography_spectrum: 0.2053446767386049
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2093479512259364
  lightness: 0.24169745203107595
  saturation: 0.34936614078469574
  rhythmicContrast: 0.018318917136639357
purpose: []
